<?php

/**
 * mSheetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mSheetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mSheetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mSheet');
    }
}