# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#Rutas de categorias

moveDownCategory:
  url: /:sf_culture/moveDownCategory.html
  param: { module: myCategory, action: moveDown }

bringSiblingsCategory:
  url: /:sf_culture/bringSiblingsCategory/:id
  param: { module: myCategory, action: bringSiblings }
  
moveUpCategory:
  url: /:sf_culture/moveUpCategory/:id
  param: { module: myCategory, action: moveUp }

saveCategory:
  url: /:sf_culture/saveCategory.html
  param: { module: myCategory, action: save }

deleteCategory:
  url: /:sf_culture/deleteCategory/:id
  param: { module: myCategory, action: delete }

editCategory:
  url: /:sf_culture/editCategory/:id
  param: { module: myCategory, action: edit }

addCategory:
  url: /:sf_culture/addCategory,html
  param: { module: myCategory, action: add }

retrieve_categories_of_class:
  url: /:sf_culture/retrieveCategoriesOfClass.html
  param: { module: myCategory, action: retrieveCategoriesOfClass }

#Rutas del  sf guard

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
