<?php

/**
 * BasemyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $label
 * @property string $name
 * @property string $description
 * @property string $object_class_name
 * @property integer $my_category_parent_id
 * @property integer $priority
 * @property myCategory $myCategory
 * @property Doctrine_Collection $myCategoryObject
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getLabel()                 Returns the current record's "label" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getObjectClassName()       Returns the current record's "object_class_name" value
 * @method integer             getMyCategoryParentId()    Returns the current record's "my_category_parent_id" value
 * @method integer             getPriority()              Returns the current record's "priority" value
 * @method myCategory          getMyCategory()            Returns the current record's "myCategory" value
 * @method Doctrine_Collection getMyCategoryObject()      Returns the current record's "myCategoryObject" collection
 * @method myCategory          setId()                    Sets the current record's "id" value
 * @method myCategory          setLabel()                 Sets the current record's "label" value
 * @method myCategory          setName()                  Sets the current record's "name" value
 * @method myCategory          setDescription()           Sets the current record's "description" value
 * @method myCategory          setObjectClassName()       Sets the current record's "object_class_name" value
 * @method myCategory          setMyCategoryParentId()    Sets the current record's "my_category_parent_id" value
 * @method myCategory          setPriority()              Sets the current record's "priority" value
 * @method myCategory          setMyCategory()            Sets the current record's "myCategory" value
 * @method myCategory          setMyCategoryObject()      Sets the current record's "myCategoryObject" collection
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemyCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('object_class_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('my_category_parent_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('myCategory', array(
             'local' => 'my_category_parent_id',
             'foreign' => 'id'));

        $this->hasMany('myCategoryObject', array(
             'local' => 'id',
             'foreign' => 'my_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
              2 => 'id',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}