<?php

/**
 * BasemyAlbumVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $my_album_id
 * @property integer $user_id
 * @property integer $priority
 * @property string $description
 * @property string $src
 * @property string $code
 * @property myAlbum $myAlbum
 * @property sfGuardUser $User
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getMyAlbumId()   Returns the current record's "my_album_id" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method integer      getPriority()    Returns the current record's "priority" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method string       getSrc()         Returns the current record's "src" value
 * @method string       getCode()        Returns the current record's "code" value
 * @method myAlbum      getMyAlbum()     Returns the current record's "myAlbum" value
 * @method sfGuardUser  getUser()        Returns the current record's "User" value
 * @method myAlbumVideo setId()          Sets the current record's "id" value
 * @method myAlbumVideo setMyAlbumId()   Sets the current record's "my_album_id" value
 * @method myAlbumVideo setUserId()      Sets the current record's "user_id" value
 * @method myAlbumVideo setPriority()    Sets the current record's "priority" value
 * @method myAlbumVideo setDescription() Sets the current record's "description" value
 * @method myAlbumVideo setSrc()         Sets the current record's "src" value
 * @method myAlbumVideo setCode()        Sets the current record's "code" value
 * @method myAlbumVideo setMyAlbum()     Sets the current record's "myAlbum" value
 * @method myAlbumVideo setUser()        Sets the current record's "User" value
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemyAlbumVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_album_video');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('my_album_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('src', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('myAlbum', array(
             'local' => 'my_album_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $mymediacontentbehavior0 = new myMediaContentBehavior();
        $this->actAs($timestampable0);
        $this->actAs($mymediacontentbehavior0);
    }
}