<?php

/**
 * myNewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myNewTable extends PluginmyNewTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myNewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myNew');
    }
}