<?php

/**
 * BasemyNew
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $slug
 * @property string $title
 * @property text $copete
 * @property text $body
 * @property string $source
 * @property timestamp $publish
 * @property boolean $is_active
 * @property integer $views_count
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getSlug()        Returns the current record's "slug" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method text      getCopete()      Returns the current record's "copete" value
 * @method text      getBody()        Returns the current record's "body" value
 * @method string    getSource()      Returns the current record's "source" value
 * @method timestamp getPublish()     Returns the current record's "publish" value
 * @method boolean   getIsActive()    Returns the current record's "is_active" value
 * @method integer   getViewsCount()  Returns the current record's "views_count" value
 * @method myNew     setId()          Sets the current record's "id" value
 * @method myNew     setSlug()        Sets the current record's "slug" value
 * @method myNew     setTitle()       Sets the current record's "title" value
 * @method myNew     setCopete()      Sets the current record's "copete" value
 * @method myNew     setBody()        Sets the current record's "body" value
 * @method myNew     setSource()      Sets the current record's "source" value
 * @method myNew     setPublish()     Sets the current record's "publish" value
 * @method myNew     setIsActive()    Sets the current record's "is_active" value
 * @method myNew     setViewsCount()  Sets the current record's "views_count" value
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemyNew extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_new');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('slug', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('copete', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('source', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 128,
             ));
        $this->hasColumn('publish', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('views_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}