<?php

/**
 * myMediaContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myMediaContentTable extends PluginmyMediaContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myMediaContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myMediaContent');
    }
}