<?php

/**
 * myUploadedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myUploadedTable extends PluginmyUploadedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myUploadedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myUploaded');
    }
}