<?php

/**
 * myTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myTest');
    }
}