<?php

/**
 * myCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCategoryTable extends PluginmyCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCategory');
    }
}