<?php

/**
 * myAlbumVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myAlbumVideoTable extends PluginmyAlbumVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myAlbumVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myAlbumVideo');
    }
}