<?php

/**
 * PluginmyAlbumVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyAlbumVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyAlbumVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyAlbumVideo');
    }
}