<?php

/**
 * PluginmyMediaContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyMediaContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyMediaContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyMediaContent');
    }
    
    public function retrieveByObjectClassAndId($object_class, $object_id)
    {
      $q = $this->createQuery("q")
              ->addWhere("q.object_class_name = ?", $object_class)
              ->addWhere("q.object_id = ?", $object_id);
      
      return $q->fetchOne();
    }
    
    public function retrieveLastScalar($album_id)
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "select MAX(m.priority) + 1 AS m__0 FROM my_media_content m WHERE (m.my_album_id = ?)";
      $r = $conn->fetchOne($sql, array($album_id));
      return $r;
    }
}