<?php

/**
 * PluginmyAlbumVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmyAlbumVideo extends BasemyAlbumVideo
{

  const YOUTUBE = "youtube";
  
  const VIMEO = "vimeo";
  
  private $_metadata = null;
  
  public function preSave($event) {
    parent::preSave($event);
    
    // Tengo que averiguar de que tipo de video estamos hablando
    $type = $this->getVideoType();
    if(is_null($type))
    {
      throw new Exception("me pusieron verdura!!");
    }
    switch ($type) {
      case self::YOUTUBE:
        $metadata = $this->getYoutubeData();
        $this->setCode($metadata->code);
        break;
      case self::VIMEO:
        $object = $this->getVimeoData();
        /*
        $auxVimeo = new myVimeo();
        $auxVimeo->setUrl($this->getSrc());
        $object = $auxVimeo->getEmbedObject();
        */
        $this->setCode($object->video_id);
        break;
      default:
        break;
    }
  }

  public function getUrl($options = array())
  {
    $type = $this->getVideoType();
    switch ($type) {
      case self::YOUTUBE:
        //$metadata = $this->getYoutubeData();
        return "http://img.youtube.com/vi/".$this->getCode()."/0.jpg";
        break;
      case self::VIMEO:
        $object = $this->getVimeoData();
        return $object->thumbnail_url;
        break;
      default:
        break;
    
    }
    
  }
  
  /**
    * Return the class of this object
    *
    * @return String
    * @author Rodrigo Santellan
    */
  public function getObjectClass() 
  {
      return get_class($this);
  }  
  
  
  public function getVideoType()
  {
    if (strpos($this->getSrc(), 'youtube') > 0) {
        return self::YOUTUBE;
    } elseif (strpos($this->getSrc(), 'vimeo') > 0) {
        return self::VIMEO;
    } else {
        return NULL;
    }
  }
  
  
  public function getVimeoData()
  {
    $cache_key = $this->getObjectClass()."_".$this->getVideoType()."_".$this->getId();
    $cache = new FileCache();
    $cache->setCache($this->getObjectClass());
    if(!$this->isNew())
    {
      if($cache->isCached($cache_key))
      {
        return unserialize($cache->retrieve($cache_key));
      }
    }
    $auxVimeo = new myVimeo();
    $auxVimeo->setUrl($this->getSrc());
    $object = $auxVimeo->getEmbedObject();
    
    if(!$this->isNew())
    {
      //Antes de serializarlo lo convierto en un objecto stdObject con json_decode(json_encode($object))
      $cache->store($cache_key, serialize(json_decode(json_encode($object))));
    }
    return $object;
  }
  
  public function getYoutubeData()
  {
    $cache_key = $this->getObjectClass()."_".$this->getVideoType()."_".$this->getId();
    $cache = new FileCache();
    $cache->setCache($this->getObjectClass());
    if(!$this->isNew())
    {
      if($cache->isCached($cache_key))
      {
        return unserialize($cache->retrieve($cache_key));
      }
    }
    
    if(is_null($this->_metadata))
      {
        //
        $url = "http://gdata.youtube.com/feeds/api/videos/".$this->retrieveYoutubeCode();
        $xml = simplexml_load_file($url);
        $children = $xml->children("http://www.w3.org/2005/Atom");
        $stdObject = new stdClass();
        $stdObject->title = (string)$children->title;
        $stdObject->published = (string)$children->published;
        $stdObject->content = (string)$children->content;
        $stdObject->author = (string)$children->author->name;
        $stdObject->code = (string) $this->retrieveYoutubeCode();
        $this->_metadata = $stdObject;
        //

      }
      if(!$this->isNew())
      {
        $cache->store($cache_key, serialize($stdObject));
      }

      return $this->_metadata;
  }
  
  public function retrieveYoutubeCode()
  {
      /*preg_match(
      '/[\\?\\&]v=([^\\?\\&]+)/',
          'http://www.youtube.com/watch?v=OzHvVoUGTOM&feature=channel',
          $matches
      );*/
      // $matches[ 1 ] should contain the youtube id
      //print_r($matches);
      preg_match(
      '/[\\?\\&]v=([^\\?\\&]+)/',
          $this->getSrc(),
          $matches
      );
      // $matches[ 1 ] should contain the youtube id
      if(!isset($matches[1]))
          throw new Exception("The youtube url is invalid", 1001);
      return $matches[1];
  }
  
}