<?php

/**
 * myTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmyTest extends BasemyTest
{

  public function postSave($event) {
    parent::postSave($event);
    myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Default", "Este es el album default");
    myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Galeria", "Este es el album de las galerias");
  }

  /**
    * Return the class of this object
    *
    * @return String
    * @author Rodrigo Santellan
    */
  public function getObjectClass() 
  {
      return get_class($this);
  }  
}