<?php

/**
 * mGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mGroup');
    }
}