<?php

/**
 * mInstrumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmInstrumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mInstrumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mInstrument');
    }
}