<?php

/**
 * mSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmSong extends BasemSong
{
    public function postSave($event) 
    {
        parent::postSave($event);
        myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Cancion Publica", "Album de las canciones publicas", myAlbumHandler::MIXED, "*.mp3");
        myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Cancion Privada", "Album de las canciones privadas", myAlbumHandler::MIXED, "*.mp3");
        myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Videos", "Album de los videos online", myAlbumHandler::ONLINEVIDEOS);
        myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Guitar Pro", "Album de los archivos de Guitar Pro", myAlbumHandler::MIXED, "*.gp3, *.gp4, *.gp5, *.gp6");
        
    }
    
    
    public function postDelete($event) {
      parent::postDelete($event);
      myAlbumHandler::deleteAllAlbumsOfObject($this->getId(), $this->getObjectClass());
    }
    
    /**
    * Return the class of this object
    *
    * @return String
    * @author Rodrigo Santellan
    */
    public function getObjectClass() 
    {
      return get_class($this);
    }
}
