<?php

/**
 * BasemSheet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $m_instrument_id
 * @property integer $m_song_id
 * @property mInstrument $mInstrument
 * @property mSong $mSong
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getMInstrumentId()   Returns the current record's "m_instrument_id" value
 * @method integer     getMSongId()         Returns the current record's "m_song_id" value
 * @method mInstrument getMInstrument()     Returns the current record's "mInstrument" value
 * @method mSong       getMSong()           Returns the current record's "mSong" value
 * @method mSheet      setId()              Sets the current record's "id" value
 * @method mSheet      setMInstrumentId()   Sets the current record's "m_instrument_id" value
 * @method mSheet      setMSongId()         Sets the current record's "m_song_id" value
 * @method mSheet      setMInstrument()     Sets the current record's "mInstrument" value
 * @method mSheet      setMSong()           Sets the current record's "mSong" value
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemSheet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('musicsheet');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('m_instrument_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('m_song_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mInstrument', array(
             'local' => 'm_instrument_id',
             'foreign' => 'id'));

        $this->hasOne('mSong', array(
             'local' => 'm_song_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}