<?php

/**
 * PluginmyNew
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmyNew extends BasemyNew
{

  public function preSave($event) {
    parent::preSave($event);
    $this->setSlug(myBasicHandler::slugify($this->getTitle()));
  }
  
  public function postSave($event) {
    parent::postSave($event);
    myAlbumHandler::createAlbum($this->getId(), $this->getObjectClass(), "Default", "Este es el album default");
  }

  public function postDelete($event) {
      parent::postDelete($event);
      myAlbumHandler::deleteAllAlbumsOfObject($this->getId(), $this->getObjectClass());
  }
  
  /**
    * Return the class of this object
    *
    * @return String
    * @author Rodrigo Santellan
    */
  public function getObjectClass() 
  {
      return get_class($this);
  }
  
}