<?php

/**
 * myCategoryObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCategoryObjectTable extends PluginmyCategoryObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCategoryObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCategoryObject');
    }
}