<?php

/**
 * myCategoryObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCategoryObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCategoryObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCategoryObject');
    }
    
    public function getObjectCategoriesId($object_id, $object_class)
    {
      $sql = "select my_category_id from my_category_object where object_id = ? and object_class_name = ?";
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
      //$conn->fetchA
      return $conn->fetchArray($sql, array($object_id, $object_class));
    }
}