<?php

/**
 * myCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCategory');
    }
    
    public function retrieveCategoriesObjectClasses()
    {
      $q = $this->createQuery("myC")->select("distinct(myC.object_class_name) as object_class_name");
      $q->addWhere("myC.my_category_parent_id IS NULL");
      return $q->execute();
    }
    
    public function retrieveAllTreeOfObjectClass($objectClass, $parent_id = null)
    {
      $resultado = array();
      $q = $this->createQuery("myC");
      if(is_null($parent_id))
      {
        $q->addWhere("myC.object_class_name = ?", $objectClass);
        $q->addWhere("myC.my_category_parent_id IS NULL"); 
      }
      else 
      {
        $q->addWhere("myC.my_category_parent_id = ?", $parent_id);
      }
      foreach($q->execute() as $result)
      {
        $aux = array('category' => $result);
        $aux_res = $this->retrieveAllTreeOfObjectClass($objectClass, $result->getId());
        $aux["childs"] = $aux_res;
        $resultado[] = $aux;
      }
      return $resultado;
      
    }
}