<?php

/**
 * myUploaded
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    testing
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class myUploaded extends BasemyUploaded
{
  
  public function getUrl($options = array(), $original = false)
  {
    myCacheHandler::createCacheImage(sfConfig::get('sf_upload_dir').$this->getPath().DIRECTORY_SEPARATOR.$this->getFilename(), $options);
  }
}
