myTest:
  actAs:
    Timestampable: ~
    I18n:
      fields: [ title, body ]
      actAs:
        Sluggable: { fields: [ title ], uniqueBy: [ lang, title ] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title: 
      type: string(255)
      notnull: true 
    body: 
      type: string(4000)
      notnull: true 