myCategory:
  actAs:
    Timestampable: ~
    I18n:
      fields: [name, description]
      actAs:
        Sluggable: { fields: [name], uniqueBy: [lang, name, id] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    label:
      type: string(100)
      notnull: true
      unique: true
    name:
      type: string(100)
      notnull: true
    description:
      type: string(255)
    object_class_name:
      type: string(100)
      notnull: true
    my_category_parent_id:
      type: integer(4)
      notnull: false
    priority:
      type: integer(2)
      default: 0
  relations:
    myCategory:
      local: my_category_parent_id
      foreign: id
      type: one
      onDelete: CASCADE

myCategoryObject:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    object_id:
      type: integer(4)
      primary: true
    my_category_id:
      type: integer(4)
      primary: true
    object_class_name:
      type: string(250)
      primary: true
    priority:
      type: integer(2)
      default: 0
  relations:
    myCategory:
      local: my_category_id
      onDelete: CASCADE
