<?php

/**
 * PluginmyNewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyNewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyNewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyNew');
    }
}