myAlbum:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true  
    title:
      type: string(64)
      notnull: true
    description:
      type:	string(255)
    type:
      type: enum
      values: [Image, Video, File, Mixed]
      default: Mixed
    deleteAllowed:
      type: bool
      notnull: true
    my_file_id:
      type: integer(4)
      default: null
    object_class_name:
       type: string(128)
       notnull: true
    object_id:
       type: integer(4)
       notnull: true

       
myUploaded:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    my_album_id:
      type: integer(4)
      primary: true      
    name:
      type: string(64)
      notnull: true
    filename:
      type: string(64)
      notnull: true 
    description:
      type:	string(255)
    path:
      type: string(255)
    filetype:
      type:	string(64)
      notnull: true
    priority:
      type: integer(4)
      default: 0
  relations:
    myAlbum:
      local: my_album_id
      foreign: id
      type: one
      
myTest:
  actAs:
    Timestampable: ~
    I18n:
      fields: [ title, body ]
      actAs:
        Sluggable: { fields: [ title ], uniqueBy: [ lang, title ] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title: 
      type: string(255)
      notnull: true 
    body: 
      type: string(4000)
      notnull: true 
     