<?php

/**
 * myCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginmyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCategory');
    }
    
    public function retrieveCategoriesObjectClasses()
    {
      $q = $this->createQuery("myC")->select("distinct(myC.object_class_name) as object_class_name");
      $q->addWhere("myC.my_category_parent_id IS NULL");
      return $q->execute();
    }
    
    public function retrieveLastPriorityNumber($objectClass, $parent_id = null)
    {
        $q = $this->createQuery("myC")->select("MAX(myC.priority) as prior");
        
        if(is_null($parent_id))
        {
          $q->addWhere("myC.object_class_name = ?", $objectClass);
          $q->addWhere("myC.my_category_parent_id IS NULL"); 
        }
        else 
        {
          $q->addWhere("myC.my_category_parent_id = ?", $parent_id);
        }
        
        return $q->fetchOne(array(), Doctrine_Core::HYDRATE_SCALAR);
    }
    
    public function retrieveAllTreeOfObjectClass($objectClass, $parent_id = null)
    {
      $resultado = array();
      $q = $this->createQuery("myC");
      if(is_null($parent_id))
      {
        $q->addWhere("myC.object_class_name = ?", $objectClass);
        $q->addWhere("myC.my_category_parent_id IS NULL"); 
      }
      else 
      {
        $q->addWhere("myC.my_category_parent_id = ?", $parent_id);
      }
      $q->addOrderBy("myC.priority");
      foreach($q->execute() as $result)
      {
        $aux = array('category' => $result);
        $aux_res = $this->retrieveAllTreeOfObjectClass($objectClass, $result->getId());
        $aux["childs"] = $aux_res;
        $resultado[] = $aux;
      }
      return $resultado;
    }
    
    public function updateToNullParent($object_class, $categoryId)
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      
      $sqlMax = "select max(priority) + 1 as prioridad from my_category where object_class_name = ? and my_category_parent_id is NULL";
      
      $r = $conn->fetchOne($sqlMax, array($object_class));
      
      $sql = "UPDATE my_category SET my_category_parent_id = NULL, priority = ? WHERE id = ?";
      $conn->exec($sql, array($r, $categoryId));
    }
    
    public function retrieveSiblings($parent_id, $objectClass, $categoryId, $exclude_self = true)
    {
      $q = $this->createQuery("myC");
      if(is_null($parent_id))
      {
        $q->addWhere("myC.object_class_name = ?", $objectClass);
        $q->addWhere("myC.my_category_parent_id IS NULL"); 
      }
      else 
      {
        $q->addWhere("myC.my_category_parent_id = ?", $parent_id);
      }
      if($exclude_self)
      {
        $q->addWhere("myC.id <> ?", $categoryId);
      }
      $q->addOrderBy("myC.priority");
      return $q->execute();
    }
    
    public function retrieveAllCategoriesOfIds($id_list)
    {
      $q = $this->createQuery("myC");
      $q->whereIn("myC.id", $id_list);
      return $q->execute();
    }
}