<?php

/**
 * PluginmyAlbumVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyAlbumVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyAlbumVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyAlbumVideo');
    }
    
    public function retrieveAlbumContent($albumId, $order = "DESC", $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
      $query = $this->createQuery("q")
              ->addWhere("q.my_album_id = ?", $albumId)
              ->orderBy("q.priority ". $order);
      
      $query->setHydrationMode($hydrationMode);
      return $query->execute();
    }
}