<?php

/**
 * BasemInstrument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $mSheet
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getMSheet() Returns the current record's "mSheet" collection
 * @method mInstrument         setId()     Sets the current record's "id" value
 * @method mInstrument         setName()   Sets the current record's "name" value
 * @method mInstrument         setMSheet() Sets the current record's "mSheet" collection
 * 
 * @package    testing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemInstrument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('musicinstrument');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mSheet', array(
             'local' => 'id',
             'foreign' => 'm_instrument_id'));
    }
}